move files around, update readme, rename module
cilium/linters pull request #1
Opened 2023-07-10 19:42 UTC by rolinh

See commits for details.

2023-07-10 20:03 UTC, nathanjsweet requested changes
That should fix your "go.mod" error.

2023-07-10 20:03 UTC, nathanjsweet commented on main.go
> +	"github.com/cilium/customvet/ioreadall"
```suggestion
	"github.com/cilium/linters/ioreadall"
```

2023-07-10 20:03 UTC, nathanjsweet commented on main.go
> +	"github.com/cilium/customvet/timeafter"
```suggestion
	"github.com/cilium/linters/timeafter"
```

2023-07-11 08:15 UTC, kaworu approved these changes

2023-07-11 08:18 UTC, merged