add slowg analyzer to check inappropriate use of log/slog
cilium/linters pull request #2
Opened 2023-07-11 12:23 UTC by rolinh

2023-07-12 20:21 UTC, nathanjsweet requested changes
Will this analyzer run by default? If so, I'm worried that it will break the cilium repo.
Everything else looks good.

2023-07-12 20:55 UTC, rolinh commented
> Will this analyzer run by default?

I've enabled it by default, yes.

> If so, I'm worried that it will break the cilium repo.

In which way? I don't understand your concern as Cilium is not even using log/slog yet 🤔

2023-07-14 07:17 UTC, rolinh commented
Converted back to draft, the log functions were renamed from `XXXCtx` to `XXXContext` and thus the linter needs an update.

2023-07-14 08:14 UTC, rolinh commented
CI is now failing as there is no tagged release of Go 1.21 that includes [this change](https://github.com/golang/go/commit/3f8b04bfb541127704ec5c33a52294fe3c6ebea4) yet. Unfortunately, it looks like we cannot specify `tip` or a commit sha as the Go version to use in the matrix of tests.

2023-07-14 11:41 UTC, rolinh commented
I'll mark the PR as ready to merge. CI should turn green once we update Go 1.21 to the RC.3.

2023-07-14 12:52 UTC, kaworu approved these changes

2023-07-18 12:12 UTC, rolinh commented on ioreadall/io_readall.go
> +	URL:      "https://github.com/cilium/linters/ioreadall",
Ah good point. Well, there's no readme in that directory, let's simply use `https://github.com/cilium/linters`.

2023-07-18 12:17 UTC, rolinh commented
Go v1.21.0-rc.3 is out so I updated the Go matrix in the CI tests and, as expected, the tests now pass.

@nathanjsweet Could you please check this PR again or give a rationale as to why you think we shouldn't merge it as is?

2023-07-18 17:41 UTC, merged